version: "3.8"

services:
  graph-node:
    image: graphprotocol/graph-node:v0.32.0
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - firehose
    environment:
      postgres_host: "postgres"
      postgres_user: "graph-node"
      postgres_pass: "let-me-in"
      postgres_db: "graph-node"
      ipfs: "ipfs:5001"
      GRAPH_LOG: "info"
      GRAPH_NODE_CONFIG: "/config.toml"
    volumes:
      - "./config.toml:/config.toml"
  ipfs:
    image: ipfs/kubo:v0.23.0
    ports:
      - '5001:5001'
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
  firehose:
    image: tmcgroul/firehose-grpc:24
    ports:
      - '13042:13042'
    command: [ "--archive", "http://query-gateway:8002/network/bsc-mainnet",
      "--finality-confirmation", "5"
    ]
    depends_on:
      query-gateway:
        condition: service_healthy
    environment:
      RUST_LOG: "firehose_grpc=info"
  query_gateway:
    image: subsquid/query-gateway:0.2.8
    environment:
      HTTP_LISTEN_ADDR: 0.0.0.0:8002
      BOOT_NODES: >
        12D3KooWSRvKpvNbsrGbLXGFZV7GYdcrYNh4W2nipwHHMYikzV58 /dns4/testnet.subsquid.io/tcp/22345,
        12D3KooWQC9tPzj2ShLn39RFHS5SGbvbP2pEd7bJ61kSW2LwxGSB /dns4/testnet.subsquid.io/tcp/22346,
        12D3KooWQER7HEpwsvqSzqzaiV36d3Bn6DZrnwEunnzS76pgZkMU /dns4/testnet.subsquid.io/tcp/32345
      RPC_URL: https://sepolia-rollup.arbitrum.io/rpc
      CONFIG_PATH: /app/data/config/gateway-config.yml
      KEY_PATH: /app/data/keys/busdSubgraphPhaseTwo.key
      ALLOCATIONS_DB_PATH: /app/data/allocations.db
    env_file:
      - .contract-addrs
    volumes:
      - ./query-gateway:/app/data
    ports:
      - "19174:8002"
